/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pkg_test_Test */

#ifndef _Included_pkg_test_Test
#define _Included_pkg_test_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pkg_test_Test
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_pkg_test_Test_add
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
