/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pkg_test_B */

#ifndef _Included_pkg_test_B
#define _Included_pkg_test_B
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pkg_test_B
 * Method:    createB
 * Signature: ()Lpkg/test/B;
 */
JNIEXPORT jobject JNICALL Java_pkg_test_B_createB
  (JNIEnv *, jclass);

/*
 * Class:     pkg_test_B
 * Method:    initInstance
 * Signature: (Lpkg/test/B;)V
 */
JNIEXPORT void JNICALL Java_pkg_test_B_initInstance
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
