/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pkg_test_A */

#ifndef _Included_pkg_test_A
#define _Included_pkg_test_A
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pkg_test_A
 * Method:    foo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_pkg_test_A_foo
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
